### ISSUE TITLE
招商银行信用卡

### ISSUE THREAD

**Issue by mj000001** [linzhenpeng/machinelearning#1]
您好！我想问一下您在招商银行那个比赛中，main.py里有一个重点页面处理代码，重点页面放在hot_lbl_3列表中，我想知道这个重点页面是如何得到的呢？

**Comment by linzhenpeng** [comment]
重点页面处理是 根据  特征选择来的

**Comment by mj000001** [comment]
是根据lightgbm中的feature_importance()函数进行选择的么？

**Comment by linzhenpeng** [comment]
是的  还可以根据其他的   特征相关性   特征对标签分类的影响程度  等等

**Comment by mj000001** [comment]
好的，多谢
